"""implement relationships

Revision ID: 16f65587d09f
Revises: 4fa080617485
Create Date: 2024-05-15 16:44:25.920998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f65587d09f'
down_revision = '4fa080617485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('planet_id', sa.Integer(), nullable=False))
    op.add_column('missions', sa.Column('scientist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_missions_planet_id_planets'), 'missions', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key(op.f('fk_missions_scientist_id_scientists'), 'missions', 'scientists', ['scientist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_missions_scientist_id_scientists'), 'missions', type_='foreignkey')
    op.drop_constraint(op.f('fk_missions_planet_id_planets'), 'missions', type_='foreignkey')
    op.drop_column('missions', 'scientist_id')
    op.drop_column('missions', 'planet_id')
    # ### end Alembic commands ###
